import { Switch } from "react-native-gesture-handler"
import { Chat } from "../Screens/ScreensIndex"

export default {
    Welcome_to_BharatBit: 'Welcome to BharatBit',
    create_Password: "Create Password",
    change_Password: "Update Password",

    log_in: "Login",
    forgot_Password: "Forgot Password",
    Enter_your_email_send_email: "Enter your email, we will send you an email with link to recover your account",
    enterTitle: 'Enter title',
    enterDiscription: 'Enter discription',

    otp_verification: 'OTP Verification',
    enter_Six_Diagit_code: 'Enter six digit code sent on your mobile number',
    signUp_Subtitle: "You're good to go! Buy/sell crypto, set up recurring \n buys for your investments.",
    alreadyHaveAccount: "Already have an account?",
    dont_recive_otp: "Didn’t receive otp?",
    dont_have_account: "Don’t have an account?",
    by_registering_you_are_agreeing: "By registering, you are agreeing with our",
    terms_of_use: "Terms of Use",
    and: "and",
    privacy_policy: "Privacy Policy",
    crete_an_offer_to_sell_your_crypto_easily: "Create an offer to sell your crypto easily",
    want_to_sell_your_cripto: "Want to Sell your crypto",
    i_want_to_buy: "I want to buy",
    sort: "Sort",
    country: "Country",
    enterOtp: 'Enter OTP',
    sell_crypto: 'Sell Crypto',
    Modify_Offer: 'Modify Offer',
    on_the_most_secure: 'On the most secure system',
    what_you_want_to_sell: 'What you want to sell?',
    Bitcoin: 'Bitcoin',
    Ethereum: 'Ethereum',
    USDT: 'USDT',
    Bitcoin_Amount: 'Bitcoin Amount',
    Amount: 'Amount',
    Enter_Manually: 'Enter Manually',
    Available_Amount: "Available Amount:",
    Amount_From_Wallet: 'Amount From Wallet',
    Bitcoin_Amount: 'Bitcoin Amount',
    Market_price: 'Market price:',
    member_Since: 'Member Since',
    Location: 'Location',
    Payment_Method: 'Payment Method',
    UPI: 'UPI',
    Bank_transfer: 'Bank Transfer',
    IMPS: 'IMPS',
    RTGS: 'RTGS',
    PayPal: 'PayPal',
    PhonePe: 'PhonePe',
    Title: 'Title',
    Description: 'Description',
    Wallet: 'Wallet',
    Trades: 'Trades',
    Deal_Details: "Deal Details",
    Order_placed_on: "Order placed on ",
    Actions: 'Actions',
    online: "Online",
    Recieved: "Recieved",
    Paid: "Paid",
    Pending: "Pending",
    Not_Recieved: "Not Recieved",
    Raise_Dispute: "Raise a Dispute",
    orderPlacedOn: 'Order placed on',
    below_Market_Price: 'below market price',
    unread: 'Undead',
    chat: 'Chat',
    // MARK :-  Place holders
    email: 'Email',
    phoneNumb: 'Phone Number',
    firstName: "First Name",
    lasName: "Last Name",
    firstName: "First Name",
    emailAddress: "Email Address",
    searchTrade: "Search Trade",
    mobileNumber: "Mobile number",
    password: "Password",
    oldPassword: "Old Password",
    newPassword: "New Password",
    confirmNewpassword: "Confirm new Password",
    confrmPassword: "Confirm Password",
    loading: 'loading',
    // Error message
    Network_Failed: 'Oops! Something went wrong! ',
    User_Alreay_Exist: 'User Already Exist!',
    Button_Ok: 'OK',
    My_Offers: 'My Offers',
    Total: "Total",
    Wallet: 'Wallet',
    Offer_Details:'Offer Details',
    Transactions:'Transactions',
    Transaction_Id:'Transaction ID',
    Time:'Time',
    Transaction_Detail:'Transaction Detail',

// MARK: ---- New Names Rigt@Rise

Right:'Right',
toRise:'2Rise',
dashBoardTitle:'A sliding demo text is to be displayed here with a transition.',

About_Us:'About Us',
Training:'Training',
Consulting:'Consulting',
POSH:'POSH',
RKT_Foundation:'RKT Foundation',
Downloads:'Downloads',
Videos:'Videos',
Conact_US:'Contact Us'

}

