export default{
Log_in:'Log in',
ResendOtp:'Resend OTP',
Signup: 'Signup',
Send: 'Send',
continue:'Continue',
Next:'Next',
forget_password:'Forgot password',
Buy:'Buy',
Completed:'Completed',
Pending:'Pending',
createOfffer:'CREATE OFFER',
changePassword:'Change Password',
editProfile:'Edit Profile',
tradeHistory:'Trade History',
support:'Support',
logout:'Logout',
Place_Sell_Order:'Place Sell Order',
Update_Place_Sell_Order:'Update & Place Sell Order',
Cancel:"Cancel",
Accept:'Accept',
Delete:'Delete',
Decline:'Decline',
ok : 'OK',
Connect:"Connect",
Confirm:"Confirm",
Back:"Back",
Deposit:'Deposit',
Withdraw:'Withdraw',
Transfer:'Tranfer',
Modify_Offer:'Modify Offer',
Delete_Offer:'Delete Offer'
}